//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnakServer.Service.WcfEntities
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Highscores", Namespace="http://schemas.datacontract.org/2004/07/SnakServer.Service.WcfEntities")]
    public partial class Highscores : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private SnakServer.Service.WcfEntities.Highscore[] scoresField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public SnakServer.Service.WcfEntities.Highscore[] scores
        {
            get
            {
                return this.scoresField;
            }
            set
            {
                this.scoresField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Highscore", Namespace="http://schemas.datacontract.org/2004/07/SnakServer.Service.WcfEntities")]
    public partial class Highscore : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string levelNameField;
        
        private string playerNameField;
        
        private int scoreField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string levelName
        {
            get
            {
                return this.levelNameField;
            }
            set
            {
                this.levelNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string playerName
        {
            get
            {
                return this.playerNameField;
            }
            set
            {
                this.playerNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int score
        {
            get
            {
                return this.scoreField;
            }
            set
            {
                this.scoreField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServerService")]
public interface IServerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetSampleData", ReplyAction="http://tempuri.org/IServerService/GetSampleDataResponse")]
    int GetSampleData(int input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetSampleData", ReplyAction="http://tempuri.org/IServerService/GetSampleDataResponse")]
    System.Threading.Tasks.Task<int> GetSampleDataAsync(int input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SaveHighscore", ReplyAction="http://tempuri.org/IServerService/SaveHighscoreResponse")]
    void SaveHighscore(string playerName, string levelName, int score);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/SaveHighscore", ReplyAction="http://tempuri.org/IServerService/SaveHighscoreResponse")]
    System.Threading.Tasks.Task SaveHighscoreAsync(string playerName, string levelName, int score);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/getHighscoresForLevel", ReplyAction="http://tempuri.org/IServerService/getHighscoresForLevelResponse")]
    SnakServer.Service.WcfEntities.Highscores getHighscoresForLevel(string levelName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/getHighscoresForLevel", ReplyAction="http://tempuri.org/IServerService/getHighscoresForLevelResponse")]
    System.Threading.Tasks.Task<SnakServer.Service.WcfEntities.Highscores> getHighscoresForLevelAsync(string levelName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/getHighscoresForPlayer", ReplyAction="http://tempuri.org/IServerService/getHighscoresForPlayerResponse")]
    SnakServer.Service.WcfEntities.Highscores getHighscoresForPlayer(string playerName);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/getHighscoresForPlayer", ReplyAction="http://tempuri.org/IServerService/getHighscoresForPlayerResponse")]
    System.Threading.Tasks.Task<SnakServer.Service.WcfEntities.Highscores> getHighscoresForPlayerAsync(string playerName);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerServiceChannel : IServerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerServiceClient : System.ServiceModel.ClientBase<IServerService>, IServerService
{
    
    public ServerServiceClient()
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetSampleData(int input)
    {
        return base.Channel.GetSampleData(input);
    }
    
    public System.Threading.Tasks.Task<int> GetSampleDataAsync(int input)
    {
        return base.Channel.GetSampleDataAsync(input);
    }
    
    public void SaveHighscore(string playerName, string levelName, int score)
    {
        base.Channel.SaveHighscore(playerName, levelName, score);
    }
    
    public System.Threading.Tasks.Task SaveHighscoreAsync(string playerName, string levelName, int score)
    {
        return base.Channel.SaveHighscoreAsync(playerName, levelName, score);
    }
    
    public SnakServer.Service.WcfEntities.Highscores getHighscoresForLevel(string levelName)
    {
        return base.Channel.getHighscoresForLevel(levelName);
    }
    
    public System.Threading.Tasks.Task<SnakServer.Service.WcfEntities.Highscores> getHighscoresForLevelAsync(string levelName)
    {
        return base.Channel.getHighscoresForLevelAsync(levelName);
    }
    
    public SnakServer.Service.WcfEntities.Highscores getHighscoresForPlayer(string playerName)
    {
        return base.Channel.getHighscoresForPlayer(playerName);
    }
    
    public System.Threading.Tasks.Task<SnakServer.Service.WcfEntities.Highscores> getHighscoresForPlayerAsync(string playerName)
    {
        return base.Channel.getHighscoresForPlayerAsync(playerName);
    }
}
