//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IServerService")]
public interface IServerService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetSampleData", ReplyAction="http://tempuri.org/IServerService/GetSampleDataResponse")]
    int GetSampleData(int input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServerService/GetSampleData", ReplyAction="http://tempuri.org/IServerService/GetSampleDataResponse")]
    System.Threading.Tasks.Task<int> GetSampleDataAsync(int input);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IServerServiceChannel : IServerService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ServerServiceClient : System.ServiceModel.ClientBase<IServerService>, IServerService
{
    
    public ServerServiceClient()
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ServerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetSampleData(int input)
    {
        return base.Channel.GetSampleData(input);
    }
    
    public System.Threading.Tasks.Task<int> GetSampleDataAsync(int input)
    {
        return base.Channel.GetSampleDataAsync(input);
    }
}
